services:
  BFACPCloudflareSync:
    container_name: BFACPCloudflareSync
    build:
      context: .
      dockerfile: Dockerfile
    image: bfacpcloudflaresync:local
    restart: unless-stopped
    volumes:
      - ./config.ini:/usr/src/app/config.ini
    security_opt:
      - no-new-privileges
    mem_limit: 500M
    mem_reservation: 250M
